// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/account" | "/admin" | "/dashboard" | "/dashboard/classes" | "/dashboard/materials" | "/dashboard/scores" | "/features" | "/features/classroom-games" | "/features/classroom-management" | "/features/group-matching" | "/features/group-matching/create" | "/features/group-matching/join" | "/features/group-matching/manage" | "/features/group-matching/manage/[sessionId]" | "/features/group-matching/manage/[sessionId]/view" | "/features/materials" | "/features/student" | "/features/student/materials" | "/features/student/review" | "/features/student/scores" | "/features/student/submission" | "/features/topic-picker" | "/features/topic-picker/create" | "/features/topic-picker/join" | "/features/topic-picker/manage" | "/features/topic-picker/manage/[sessionId]" | "/features/topic-picker/manage/[sessionId]/result" | "/features/topic-picker/manage/[sessionId]/view" | "/file-upload" | "/files" | "/files/upload" | "/library" | "/login" | "/privacy" | "/terms" | "/waiting"
type PageRoutes = never
type LayoutRoutes = "/" | "/features/student"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/account": {}
  "/admin": {}
  "/dashboard": {}
  "/dashboard/classes": {}
  "/dashboard/materials": {}
  "/dashboard/scores": {}
  "/features": {}
  "/features/classroom-games": {}
  "/features/classroom-management": {}
  "/features/group-matching": {}
  "/features/group-matching/create": {}
  "/features/group-matching/join": {}
  "/features/group-matching/manage": {}
  "/features/group-matching/manage/[sessionId]": { "sessionId": string; }
  "/features/group-matching/manage/[sessionId]/view": { "sessionId": string; }
  "/features/materials": {}
  "/features/student": {}
  "/features/student/materials": {}
  "/features/student/review": {}
  "/features/student/scores": {}
  "/features/student/submission": {}
  "/features/topic-picker": {}
  "/features/topic-picker/create": {}
  "/features/topic-picker/join": {}
  "/features/topic-picker/manage": {}
  "/features/topic-picker/manage/[sessionId]": { "sessionId": string; }
  "/features/topic-picker/manage/[sessionId]/result": { "sessionId": string; }
  "/features/topic-picker/manage/[sessionId]/view": { "sessionId": string; }
  "/file-upload": {}
  "/files": {}
  "/files/upload": {}
  "/library": {}
  "/login": {}
  "/privacy": {}
  "/terms": {}
  "/waiting": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/features/student": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
