// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account">> = Specific
  const handler = {} as typeof import("../../src/app/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/classes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/classes">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/classes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/materials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/materials">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/materials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/scores/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/scores">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/scores/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/features/classroom-games/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/features/classroom-games">> = Specific
  const handler = {} as typeof import("../../src/app/features/classroom-games/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/features/classroom-management/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/features/classroom-management">> = Specific
  const handler = {} as typeof import("../../src/app/features/classroom-management/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/features/group-matching/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/features/group-matching/create">> = Specific
  const handler = {} as typeof import("../../src/app/features/group-matching/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/features/group-matching/join/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/features/group-matching/join">> = Specific
  const handler = {} as typeof import("../../src/app/features/group-matching/join/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/features/group-matching/manage/[sessionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/features/group-matching/manage/[sessionId]">> = Specific
  const handler = {} as typeof import("../../src/app/features/group-matching/manage/[sessionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/features/group-matching/manage/[sessionId]/view/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/features/group-matching/manage/[sessionId]/view">> = Specific
  const handler = {} as typeof import("../../src/app/features/group-matching/manage/[sessionId]/view/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/features/group-matching/manage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/features/group-matching/manage">> = Specific
  const handler = {} as typeof import("../../src/app/features/group-matching/manage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/features/group-matching/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/features/group-matching">> = Specific
  const handler = {} as typeof import("../../src/app/features/group-matching/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/features/materials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/features/materials">> = Specific
  const handler = {} as typeof import("../../src/app/features/materials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/features/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/features">> = Specific
  const handler = {} as typeof import("../../src/app/features/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/features/student/materials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/features/student/materials">> = Specific
  const handler = {} as typeof import("../../src/app/features/student/materials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/features/student/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/features/student">> = Specific
  const handler = {} as typeof import("../../src/app/features/student/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/features/student/review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/features/student/review">> = Specific
  const handler = {} as typeof import("../../src/app/features/student/review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/features/student/scores/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/features/student/scores">> = Specific
  const handler = {} as typeof import("../../src/app/features/student/scores/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/features/student/submission/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/features/student/submission">> = Specific
  const handler = {} as typeof import("../../src/app/features/student/submission/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/features/topic-picker/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/features/topic-picker/create">> = Specific
  const handler = {} as typeof import("../../src/app/features/topic-picker/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/features/topic-picker/join/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/features/topic-picker/join">> = Specific
  const handler = {} as typeof import("../../src/app/features/topic-picker/join/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/features/topic-picker/manage/[sessionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/features/topic-picker/manage/[sessionId]">> = Specific
  const handler = {} as typeof import("../../src/app/features/topic-picker/manage/[sessionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/features/topic-picker/manage/[sessionId]/result/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/features/topic-picker/manage/[sessionId]/result">> = Specific
  const handler = {} as typeof import("../../src/app/features/topic-picker/manage/[sessionId]/result/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/features/topic-picker/manage/[sessionId]/view/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/features/topic-picker/manage/[sessionId]/view">> = Specific
  const handler = {} as typeof import("../../src/app/features/topic-picker/manage/[sessionId]/view/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/features/topic-picker/manage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/features/topic-picker/manage">> = Specific
  const handler = {} as typeof import("../../src/app/features/topic-picker/manage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/features/topic-picker/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/features/topic-picker">> = Specific
  const handler = {} as typeof import("../../src/app/features/topic-picker/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/file-upload/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/file-upload">> = Specific
  const handler = {} as typeof import("../../src/app/file-upload/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/files/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/files">> = Specific
  const handler = {} as typeof import("../../src/app/files/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/files/upload/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/files/upload">> = Specific
  const handler = {} as typeof import("../../src/app/files/upload/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/library/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/library">> = Specific
  const handler = {} as typeof import("../../src/app/library/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../src/app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/waiting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/waiting">> = Specific
  const handler = {} as typeof import("../../src/app/waiting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/features/student/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/features/student">> = Specific
  const handler = {} as typeof import("../../src/app/features/student/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
